Salesforce Training org/objects/Class__c.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <referenceTo>School__c</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>Classes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Salesforce Training org/objects/School__c.object
<CustomObject>
    <fields>
        <fullName>No_Of_Class__c</fullName>
        <label>No Of Class</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>No_Of_Student__c</fullName>
        <label>No Of Student</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>School</label>
    <nameField>
        <label>School Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schools</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Salesforce Training org/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School</label>
        <referenceTo>School__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Salesforce Training org/classes/AssessmentStudentHandler_Test.cls
/**
 * Purpose     : Test class of Practice Assessment Questions
 * 
 * Created By  : Nikunj jain
 * 
 * Create Date : 20-03-2023
 * 
 * Resion Log  :
 *
*/
@isTest(seeAllData=false)
public class AssessmentStudentHandler_Test {
    
    @testsetup static void setup()
    {
        School__c sch=new School__c();
        sch.Name='New School';
        insert sch;
        
        Class__c cl=new Class__c();
        cl.Name='First Class';
        cl.School__c=sch.id;
        insert cl;
        
        Class__c cl1=new Class__c();
        cl1.Name='Second Class';
        cl1.School__c=sch.id;
        insert cl1;
        
        Student__c std=new Student__c();
        std.Name='Std';
        std.School__c=sch.id;
        std.Class__c=cl.Id;
        insert std;
        
        Student__c std1=new Student__c();
        std1.Name='Std';
        std1.School__c=sch.id;
        std1.Class__c=cl.Id;
        insert std1;
        
        
        Student__c std2=new Student__c();
        std2.Name='Std';
        std2.School__c=sch.id;
        std2.Class__c=cl.Id;
        insert std2;
        
        
    }
    
    @isTest(seeAllData=false)
    public static void testupdationOfStudent()
    {
        List<School__c>listOfSchool=[SELECT Id, No_Of_Student__c FROM School__c];
        List<Class__c>listOfClass=[SELECT Id FROM Class__c WHERE Name =:'Second Class'];
        System.assertEquals(1, listOfSchool.size());
        
        Test.startTest();
        
        Student__c std3=new Student__c();
        std3.Name='ji';
        std3.School__c=listOfSchool[0].id;
        std3.Class__c=listOfClass[0].id;
        insert std3;
        
        
        
        Test.stopTest();
        List<School__c>updateListOfSchool=[SELECT Id, No_Of_Student__c,No_Of_Class__c FROM School__c];
        System.assertEquals(4, updateListOfSchool[0].No_Of_Student__c);
        
    }
    
}