Salesforce Training org/objects/Class__c.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <referenceTo>School__c</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>Classes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Salesforce Training org/objects/School__c.object
<CustomObject>
    <fields>
        <fullName>No_Of_Teachers__c</fullName>
        <label>No Of Teachers</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>School</label>
    <nameField>
        <label>School Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schools</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Salesforce Training org/classes/Queueable_UpdateUserWithHerokuApp_Test.cls
/*
 * Purpose       : Test Class of Queueable Job Class
 * 
 * Created By    : Nikunj jain
 * 
 * Created Date  : 12-04-2023
 * 
 * Version       : V_0.1
*/

@isTest(seeAllData=false)
public class Queueable_UpdateUserWithHerokuApp_Test {
    
    @testsetup static void  setup()
    {
        School__c schl = new School__c();
        schl.Name='New School';
        schl.No_Of_Teachers__c=5;
        insert schl;
        
        Class__c cl = new Class__c();
        cl.Name='New Class';
        cl.School__c=schl.Id;
        insert cl;
    }
    
    @isTest(SeeAllData=false)
    public static void testQueueable_UpdateUserWithHerokuApp()
    {
        List<User> listOfUsers=[SELECT Id, Heroku_App_Response__c FROM User
                                WHERE Id=:System.Label.INTEGERATION_USER_RECORD_ID
                                AND IsActive=true];
        System.assertEquals(1,listOfUsers.size());
        set<Id>setIds = new set<Id>();
        List<School__c> listOfSch=[Select Id,No_Of_Teachers__c from School__c WHERE Name='New School'];
        for(School__c sc :listOfSch)
        {
           setIds.add(sc.id);            
        }
        Test.startTest();
        Queueable_UpdateUserWithHerokuAppDetails job=new Queueable_UpdateUserWithHerokuAppDetails(setIds);
        Id jobId = System.enqueueJob(job);
        System.Assert(jobId!=null);
        Queueable_UpdateUserWithHerokuAppDetails job1=new Queueable_UpdateUserWithHerokuAppDetails(setIds,'Second Job');
        Id jobIds = System.enqueueJob(job1);
        System.Assert(jobIds!=null);
        
        Test.stopTest();
        
    }

}