Salesforce Training org/objects/Class__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Board__c</fullName>
        <label>Board</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Board</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <referenceTo>School__c</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>Classes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Salesforce Training org/objects/School__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Its shows about the real-time status of the school.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>School</label>
    <nameField>
        <label>School Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schools</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Salesforce Training org/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Active_Student__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active Student</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School_Name__c</fullName>
        <label>School Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School</label>
        <referenceTo>School__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Salesforce Training org/globalValueSets/Board.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>CBSE</fullName>
    </customValue>
    <customValue>
        <fullName>ICSE</fullName>
    </customValue>
    <customValue>
        <fullName>SBSE</fullName>
    </customValue>
    <description>This board here multiple state board you can pick.</description>
    <masterLabel>Board</masterLabel>
</GlobalValueSet>

Salesforce Training org/classes/SchoolClassController.cls
/*
 * Purpose      : Wrapper Class of Class And Students
 * 
 * Created By   : Nikunj Jain
 * 
 * Created Date : 20-05-2023
 * 
 * Version      : V_0.1
 * 
 * Story        : 
 */ 

public class SchoolClassController {
    
    // This Wrapper will be Execute  Get Record on invoked by Function
    @AuraEnabled(cacheable=false)
    public static ResponseWrapper getALLSchoolWithClass(String SchoolId)
    {
        List<ClassStudentListWrapper> schlWrapperList = new  List<ClassStudentListWrapper>();
        ResponseWrapper rw = new ResponseWrapper();
        try
        {
            
            
            List<Class__c> listOfClass = [SELECT Id,Name,Active__c,Board__c,CreatedById,LastModifiedById,(SELECT Id, Name, School_Name__c,Active_Student__c FROM Students__r) FROM Class__c WHERE School__c =:SchoolId];
            
            if(!listOfClass.isEmpty())
            {
                for(Class__c cl : listOfClass)
                {
                    ClassStudentListWrapper clsw = new ClassStudentListWrapper();
                    clsw.clRecord =cl;
                    clsw.listOfStudents = cl.Students__r;
                    clsw.sizeOfStudents =cl.Students__r.size();
                    schlWrapperList.add(clsw);
                }
                rw.setBody(schlWrapperList);
                
            }
        //return schlWrapperList;
        }
        catch(Exception ex)
        {
            rw.setError(ex.getMessage());
        }
        return rw;
    }
    
    public class ClassStudentListWrapper
    {
        @AuraEnabled
        public Class__c clRecord{get; set;}
        @AuraEnabled
        public List<Student__c> listOfStudents{get; set;}
        @AuraEnabled
        public integer sizeOfStudents{get; set;}
    }
    
    
    
    @AuraEnabled(cacheable=false)
    public static boolean deleteStudentRec(String studentId)
    {
        System.debug('studentId----'+studentId);
        List<Student__c> listOfDeleteStudent =[ SELECT Id FROM Student__c WHERE Id =:studentId ];
        
                    
        
            if(listOfDeleteStudent!=null)
            {
                System.debug('listOfDeleteStudent---'+listOfDeleteStudent);
                delete listOfDeleteStudent;
                return true;
            }
           
        System.debug('listOfDeleteStudent---'+listOfDeleteStudent);
        return false;
    }
    @AuraEnabled(cacheable=true)
    public static boolean updateRec(String recIds, Boolean checkBox)
    {
        System.debug('Yes inside method');
      
        System.debug('recIds'+recIds+'checkBox'+checkBox);
        if(String.isNotEmpty(recIds))
        {
            Student__c std= new Student__c();
            std.id=recIds;
            std.Active_Student__c=checkBox;
            update std;
            return true;
        }
        return false;
    }

}