Salesforce Training org/objects/Class__c.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <referenceTo>School__c</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>Classes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Salesforce Training org/objects/School__c.object
<CustomObject>
    <label>School</label>
    <nameField>
        <label>School Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schools</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Salesforce Training org/classes/AssessmentClassHandler.cls
/**
 * Purpose     : Practice
 * 
 * Created By  : Nikunj jain
 * 
 * Create Date :20-03-2023
 * 
 * Resion Log  :
 *
*/
public class AssessmentClassHandler {
    public static void insertionAndDeletionOfClass(List<Class__c>listOfClass, Map<Id,Class__c>mapOfClassDeatils)
    {
        System.debug('listOfClass------------.'+listOfClass);
        System.debug('mapOfClassDeatils------------.'+mapOfClassDeatils);
        
        if(listOfClass != null || mapOfClassDeatils != null)
        {
            List<Id>listOfParentId=new List<Id>();
            
            System.debug('-----------------Setup 1 clear');
            
            for(Class__c cl : listOFClass != null ? listOfClass : mapOfClassDeatils.values())
            {
                listOfParentId.add(cl.school__c);
            }
            if(listOfParentId.size() > 0 && listOfParentId != null)
            {
               System.debug('-----------------Setup 2 clear And Call');
               AssesmentPractice.NoOfClassesEasyWayTo(listOfParentId[0]);
            }
        }
    }
    

}