Salesforce Training org/objects/Class__c.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <referenceTo>School__c</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>Classes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Salesforce Training org/objects/School__c.object
<CustomObject>
    <label>School</label>
    <nameField>
        <label>School Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schools</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Salesforce Training org/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School</label>
        <referenceTo>School__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Salesforce Training org/classes/DyanmicWayToDealWithCollections.cls
/*
 * Purpose       : Write Apex Class Dyanmic Way to Deal with Collection 
 * 
 * Created By    : Nikunj jain
 * 
 * Created Date  : 06-04-2023
 * 
 * Version       : V_0.1
 */


  
public Without Sharing class DyanmicWayToDealWithCollections {
    
 
    Map<String,Map<String,List<String>>>mapOfStudentRelatedList;
    
    public  DyanmicWayToDealWithCollections(){
        Map<String,Map<String,List<String>>>mapOfStudentRelatedList=new Map<String,Map<String,List<String>>>();
        
        for(Student__c str: [SELECT Id, Name, Class__r.Name, Class__r.School__r.Name FROM Student__c WHERE Class__r.Name !=null AND Class__r.School__r.Name !=null])
        {
            if(mapOfStudentRelatedList.containsKey(str.Class__r.School__r.Name)){
                if(mapOfStudentRelatedList.get(str.Class__r.School__r.Name).containsKey(str.class__r.Name))
                {
                    mapOfStudentRelatedList.get(str.Class__r.School__r.Name).get(str.class__r.Name).add(str.Name);
                }
                 else
                {
                    mapOfStudentRelatedList.get(str.Class__r.School__r.Name).put(str.Class__r.Name, new List<String>());
                }
               
            }
            else{
                
                Map<String,List<String>>mapOfClassWithStudent=new Map<String,List<String>>();
                if(mapOfClassWithStudent.get(str.Class__r.Name)==null)
                {
                    mapOfClassWithStudent.put(str.Class__r.Name,new List<String>());
                }
                mapOfClassWithStudent.get(str.Class__r.Name).add(Str.Name);
                mapOfStudentRelatedList.put(str.Class__r.School__r.Name,mapOfClassWithStudent);
            }
        }
        System.debug('@@@@-------'+mapOfStudentRelatedList);
        
        /*
        for(String s:mapOfStudentRelatedList.KeySet()){
            System.debug('@@@@-------'+mapOfStudentRelatedList.KeySet()));
        }*/
    }

}