Salesforce Training org/objects/Class__c.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <referenceTo>School__c</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>Classes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Salesforce Training org/objects/School__c.object
<CustomObject>
    <fields>
        <fullName>No_Of_Class__c</fullName>
        <label>No Of Class</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>No_Of_Student__c</fullName>
        <label>No Of Student</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>School</label>
    <nameField>
        <label>School Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schools</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Salesforce Training org/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School</label>
        <referenceTo>School__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Salesforce Training org/classes/AssessmentSchoolHandler.cls
/**
 * Purpose     : class of Practice Assessment Questions
 * 
 * Created By  : Nikunj jain
 * 
 * Create Date : 20-03-2023
 * 
 * Resion Log  :
 *
*/
public class AssessmentSchoolHandler {
    
    public static void upadteNoOfStudentInBeforeCase(List<School__c>listOfSchool, Map<Id,School__c>mapOfSchool)
    {
        if(mapOfSchool != null || listOfSchool != null)
        {
            Set<id>setOfSchoolId=new Set<id>();
            for(School__c sch:listOfSchool)
            {
                if(sch.No_Of_Student__c != null && sch.No_Of_Student__c != mapOfSchool.get(sch.id).No_Of_Student__c)
                {
                    setOfSchoolId.add(Sch.id);
                }
            }
            
            if(setOfSchoolId != null && setOfSchoolId.size() > 0)
            {
               Map<Id,Integer>mapOfStudentCount=new Map<Id,Integer>();
               for(Student__c std : [SELECT Id, Class__c, School__c FROM Student__c WHERE
                                     Class__c != null 
                                     AND School__c =:setOfSchoolId ])
               {
                   if(!mapOfStudentCount.ContainsKey(std.School__c))
                   {
                       mapOfStudentCount.put(std.School__c,1);
                   }
                   else
                   {
                       mapOfStudentCount.put(std.School__c,mapOfStudentCount.get(std.School__c)+1);
                   }
                  
               }
                if(mapOfStudentCount != null)
                {
                    for(School__c sch: listOfSchool)
                    {
                         if(mapOfStudentCount.ContainsKey(sch.id))
                        {
                            sch.No_of_Student__c=mapOfStudentCount.get(sch.id);
                        }
                        else
                        {
                            
                            sch.No_of_Student__c=0;
                        }
                    }
                }
                
            }
        }
    }
    public static void upadteNoOfClassInBeforeCase(List<School__c>listOfSchool, Map<Id,School__c>mapOfSchool)
    {
        if(mapOfSchool != null || listOfSchool != null)
        {
            Map<Id,Integer>mapOfSchoolDetails=new Map<Id,Integer>();
            for(School__c sch :listOfSchool)
            {
                mapOfSchoolDetails.put(Sch.id, 0);
            }
            if(mapOfSchoolDetails != null)
            {
                for(Class__c cl: [SELECT ID, School__c FROM Class__c WHERE School__c =:mapOfSchoolDetails.KeySet()])
                {
                    if(!mapOfSchoolDetails.ContainsKey(cl.School__c))
                   {
                       mapOfSchoolDetails.put(cl.School__c,1);
                   }
                   else
                   {
                       mapOfSchoolDetails.put(cl.School__c,mapOfSchoolDetails.get(cl.School__c)+1);
                   }
                }
                if(mapOfSchoolDetails != null)
                {
                    for(School__c std : listOfSchool)
                    {
                        if(mapOfSchoolDetails.ContainsKey(std.id))
                        {
                            std.No_Of_Class__c=mapOfSchoolDetails.get(std.id);
                        }
                        else
                        {
                            std.No_Of_Class__c=0;
                        }
                    }
                }
            }
        }
    }

}