Salesforce Training org/objects/Class__c.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <referenceTo>School__c</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>Classes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Salesforce Training org/objects/School__c.object
<CustomObject>
    <label>School</label>
    <nameField>
        <label>School Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schools</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Salesforce Training org/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School</label>
        <referenceTo>School__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Salesforce Training org/classes/Batch_updateOrphanStudent_Test.cls
/*
 * Purpose       : Write Test Class Of Batch Class Update Field Of Orphone Student 
 * 
 * Created By    : Nikunj jain
 * 
 * Created Date  : 07-04-2023
 * 
 * Revision Log  : V_1.0 Created 07/04/2023 
 * 
 */ 


@isTest(SeeALLData=false)
public class Batch_updateOrphanStudent_Test {
    
    @testsetup static void setup()
    {
         List<Student__c>Students=TestDataFactory.createListOfStudentsTestData();
    }

    @isTest(SeeALLData=false)
    public static void checkOrphanStudent()
    {
        List<Student__c>listofStd=[SELECT Id, Name FROM Student__c  ];
        
        System.assertEquals(5,listofStd.size());
        
        for(Student__c std: listofStd)
        {
            std.class__c =null;
            std.school__c =null;
        }
        
        Utilities.BypassAllTriggers=true;
        update listofStd;
        Utilities.BypassAllTriggers=false;
        
        Test.startTest();
        Batch_UpdateOrphanStudent batchOforphanStd= new Batch_UpdateOrphanStudent('SELECT id, Name FROM Student__c WHERE Class__c =null AND School__c =null AND Class__r.school__c=null');
        Database.executeBatch(batchOforphanStd, 100);
        Test.stopTest();
        System.assertEquals(5,[SELECT Count() FROM Student__c WHERE Class__c=null AND School__c =null]);
        System.assertEquals(5, listofStd.size());
        System.assertEquals(1,Batch_UpdateOrphanStudent.emailLimits);
    }
}