Salesforce Training org/objects/Class__c.object
<CustomObject>
    <fields>
        <fullName>Board__c</fullName>
        <label>Board</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Board</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <referenceTo>School__c</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>Classes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <recordTypes>
        <fullName>CBSE</fullName>
        <active>true</active>
        <description>Central Board of Secondary Education</description>
        <label>CBSE</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Salesforce Training org/objects/School__c.object
<CustomObject>
    <fields>
        <fullName>No_Of_Class__c</fullName>
        <label>No Of Class</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>No_Of_Student__c</fullName>
        <label>No Of Student</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>School</label>
    <nameField>
        <label>School Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schools</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Salesforce Training org/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School</label>
        <referenceTo>School__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Salesforce Training org/globalValueSets/Board.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>CBSE</fullName>
    </customValue>
    <customValue>
        <fullName>ICSE</fullName>
    </customValue>
    <customValue>
        <fullName>SBSE</fullName>
    </customValue>
    <description>This board here multiple state board you can pick.</description>
    <masterLabel>Board</masterLabel>
</GlobalValueSet>

Salesforce Training org/classes/CountsManager_Test.cls
@isTest(seeAllData=false)
public class CountsManager_Test {
    
    @Testsetup
    public static void setUp()
    {
        School__c schl=new School__c();
        schl.Name='JPS6';
        insert schl;
        
        Class__c cl=new Class__c();
        cl.Name='first class';
        cl.Board__c='CBSE';
        cl.School__c=schl.Id;
        insert cl;
        
        List<Student__c>listOdStudents=new List<Student__c>();
        Student__c std=new Student__c();
        std.Name='Nikunj';
        std.Class__c=cl.Id;
        std.School__c=schl.Id;
        listOdStudents.add(std);
        
        Student__c std1=new Student__c();
        std1.Name='Nikunj';
        std1.Class__c=cl.Id;
        std1.School__c=schl.Id;
        listOdStudents.add(std1);
        
        
        Student__c std2=new Student__c();
        std2.Name='Nikunj';
        std2.Class__c=cl.Id;
        std2.School__c=schl.Id;
        listOdStudents.add(std2);
        
        insert listOdStudents;
    }
    
    @isTest(seeAllData=false)
    private static void testNoOfStudentAndClass()
    {
        List<School__c> listofSchoolsDetails = [SELECT Id, Name, No_Of_Student__c, No_Of_Class__c FROM School__c];
        Set<id>setofSchlIds=new Set<id>();
        
        for(School__c schl:listofSchoolsDetails)
        {
            setofSchlIds.add(schl.id);
        }
        
        System.assertEquals(1, listofSchoolsDetails.size());
        
        Test.startTest();
        CountManagerOld.updateNoOfStudentsDetails(listofSchoolsDetails[0].Name);
        for(Id idss : setofSchlIds)
        {
            CountManagerOld.updateNoOfClassesDetails(idss);
        }
        Test.stopTest();
        List<School__c> listofSchoolsDetails1 = [SELECT Id, Name, No_Of_Student__c, No_Of_Class__c FROM School__c];
        System.debug(listofSchoolsDetails);
        System.assertEquals(3,listofSchoolsDetails1[0].No_Of_Student__c);
        System.assertEquals(1,listofSchoolsDetails1[0].No_Of_Class__c);
    }
}