Salesforce Training org/objects/Class__c.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <referenceTo>School__c</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>Classes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Salesforce Training org/objects/School__c.object
<CustomObject>
    <fields>
        <fullName>No_Of_Class__c</fullName>
        <label>No Of Class</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>School</label>
    <nameField>
        <label>School Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schools</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Salesforce Training org/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School</label>
        <referenceTo>School__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Salesforce Training org/classes/ClassTriggerHandler.cls
/**
 * Purpose       : Trigger handler Class of Class Object
 * 
 * Created By    : Nikunj jain
 * 
 * Created Date  : 03-04-2023
 * 
 * Version       : V_01
 * 
**/

public without sharing class ClassTriggerHandler {
    
    
    
    public static void updateNumberOfClassesDetails(List<Class__c> classes, Map<Id, Class__c> mapOfOldClasses)
    {
        Set<Id> setOfParentSchools = new Set<Id>();
        
        for(Class__c cls : classes != null ? classes : mapOfOldClasses.values())
        {
            if(cls.School__c != null)
            {
                setOfParentSchools.add(cls.School__c);
            }
        }
        
        if(setOfParentSchools.size() > 0)
        {
            updateNoOfClassesDetails(setOfParentSchools);
        }
        
    }
    public static void updateNoOfClassesDetails(Set<Id> schoolId)
    {
        if(schoolId.size() >0)
        {
            List<School__c> schools = [SELECT Id, Name,
                                       (SELECT ID FROM Classes__r)
                                       FROM School__c
                                       WHERE Id =: schoolId
                                      ]; 
            if(schools.size() > 0)
            {
                for (School__c sc : schools)
                {
                    sc.No_of_Class__c = sc.Classes__r.size();
                }
                //System.debug('@@@@ schools ' + schools);
                
                Utilities.BypassAllTriggers = true;
                update schools;
                Utilities.BypassAllTriggers = false;
            }
            else
            {
                //System.debug(System.Label.ERROR_MSG_UNABLE_TO_FIND_SCHOOL_BY_ID);
                System.debug(System.LABEL.ERROR_MSG_UNABLE_TO_FIND_SCHOOL_BY_NAME);
            }
        }
        else
        {
            //System.debug(System.Label.ERROR_MSG_SCHOOL_NAME_DETAILS_MISSING);
            System.debug(System.LABEL.ERROR_MSG_SCHOOL_DETAILS_MISSING);
        }
    }

    
    public static void ClassDeletion(List<Class__c>listOfOldClass,Map<Id,Class__c>oldMapOfClass)
    {
        for(Class__c cl:[SELECT ID FROM Class__c 
                         WHERE ID IN (SELECT Class__c FROM Student__c) 
                         AND ID IN : Trigger.old])
        {
            Trigger.oldMap.get(cl.Id).addError('You can Not Deleted class because Student is in the class');
        }
    }
    
    
    /*
   public static void showErrorWhenTryToDeleteChildRecord(List<Class__c>oldOfClass)
   {
      List<Student__c>relatedStudent=[SELECT Id FROM Student__c WHERE Class__c IN :oldOfClass];
       
      for(Class__c cl:oldOfClass)
      {
          if(relatedStudent.size()>0)
          {
              cl.addError('You can not Delete This Class Becuase have Realated Student with');
          }
      }
     
   }*/
}