Salesforce Training org/objects/Class__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Board__c</fullName>
        <label>Board</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Board</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <referenceTo>School__c</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>Classes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Salesforce Training org/objects/School__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Its shows about the real-time status of the school.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>School</label>
    <nameField>
        <label>School Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schools</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Salesforce Training org/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Active_Student__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active Student</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Custom_School_Id__c</fullName>
        <formula>CASESAFEID(  Class__r.School__c  )</formula>
        <label>Custom School Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Father_Name__c</fullName>
        <label>Father Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>School_Name__c</fullName>
        <label>School Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School</label>
        <referenceTo>School__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Salesforce Training org/globalValueSets/Board.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>CBSE</fullName>
    </customValue>
    <customValue>
        <fullName>ICSE</fullName>
    </customValue>
    <customValue>
        <fullName>SBSE</fullName>
    </customValue>
    <description>This board here multiple state board you can pick.</description>
    <masterLabel>Board</masterLabel>
</GlobalValueSet>

Salesforce Training org/classes/ClassController.cls
/**
*
*  Purpose          :   Controller Class
*
*  Created Date     :   19-05-2023
*
*  Created By       :   Nikunj jain
*
*  Revision Logs    :   V_1.0 - Created
*
**/
public class ClassController {
    @AuraEnabled(cacheable = false)
    public static List<Class__c> getClassName(String SchoolId) 
    {
        
        try
        {
            if(String.isNotBlank(SchoolId))
            {
                return [SELECT Id,Name,Active__c,Board__c,CreatedById,LastModifiedById,(SELECT Id, Name, School_Name__c,Active_Student__c,Father_Name__c FROM Students__r) FROM Class__c WHERE School__c =:SchoolId];
                
            }
            return null;
        }
        catch(Exception e)
        {
            System.debug('Error  '+e.getMessage());
        }
        return null;
    }
    
    @AuraEnabled(cacheable = false)
    public static List<Student__c> getStudentDetails(String SchoolId) 
    {
        
        try
        {
            if(String.isNotBlank(SchoolId))
            {
                return [SELECT Name ,Custom_School_Id__c FROM Student__c WHERE Custom_School_Id__c =:SchoolId];
                
            }
            return null;
        }
        catch(Exception e)
        {
            System.debug('Error  '+e.getMessage());
        }
        return null;
    }
    
    @AuraEnabled
    public static boolean massDeleteRec(List<Student__c> listofStd)
    {
        System.debug('Yes mass delete');
        delete listofStd;
        return true;
    }
    
    @AuraEnabled
    public static boolean massUpdateRec(List<Student__c> listofStd)
    {
        System.debug('Yes mass delete');
        update listofStd;
        return true;
    }
    // This Class will be Execute On delete Event
    @AuraEnabled(cacheable=false)
    public static void updateStudents (List<Student__c> mapOfStudents )
    {
        System.debug('Yes in Side Update Apex Class'+mapOfStudents);
        
        
        
       
        if(!mapOfStudents.isEmpty())
        {
            List<Student__c> finalUpdate= new List<Student__c> ();
            for(Student__c up :mapOfStudents)
            {
                Student__c std = new Student__c();
                std.Id=up.Id;
                std.Father_Name__c=up.Father_Name__c;
                finalUpdate.add(std);
            }
            if(!finalUpdate.isEmpty())
            {
                update finalUpdate;
            }
        }
        
        
    }
}