Salesforce Training org/objects/Class__c.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <referenceTo>School__c</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>Classes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Salesforce Training org/objects/School__c.object
<CustomObject>
    <fields>
        <fullName>No_Of_Class__c</fullName>
        <label>No Of Class</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>No_Of_Student__c</fullName>
        <label>No Of Student</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>School</label>
    <nameField>
        <label>School Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schools</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Salesforce Training org/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School</label>
        <referenceTo>School__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Salesforce Training org/classes/DyanmicWayToDealWithCollection_Test.cls
/*
 * Purpose       : Write Test Class Of DyanmicWayDealWithCollectrion
 * 
 * Created By    : Nikunj jain
 * 
 * Created Date  : 07-04-2023
 * 
 * Revision Log  : V_0.1  92%
 * 
 */

@isTest(SeeAllData=false)
public class DyanmicWayToDealWithCollection_Test {
    
    @testsetup Static void setup()
    {
        School__c schl=new School__c();
        schl.Name='PSL';
        insert schl;
        
       
        
       
        
        Class__c cl=new Class__c();
        cl.Name='First Class';
        cl.School__c=schl.Id;
        insert cl;
        
        Class__c cl2=new Class__c();
        cl2.Name='Second Class';
        cl2.School__c=schl.Id;
        insert cl2;
        
        List<Student__c>listOfStudent=new List<Student__c>();
        Student__c std=new Student__c();
        std.Name='nj';
        std.Class__c=cl.Id;
        std.School__c=schl.id;
        insert std;
        
        
        Student__c std1=new Student__c();
        std1.Name='nj1';
        std1.Class__c=cl.Id;
        std1.School__c=schl.id;
        insert std1;
        
        
        Student__c std2=new Student__c();
        std2.Name='nj2';
        std2.Class__c=cl2.Id;
        std2.School__c=schl.id;
        insert std2;
        
        
    }
    
    @isTest(SeeAllData=false)
    public static void testDyanmicWayToDealWithCollection()
    {
        List<School__c>listOfSchool=[SELECT Id, Name, No_Of_Student__c FROM School__c ];
        System.assertEquals(1, listOfSchool.size());
        
        System.debug('####'+listOfSchool);
        Test.startTest();
        DyanmicWayToDealWithCollections obj=new DyanmicWayToDealWithCollections();
        
        Test.stopTest();
        
        List<School__c>updateListOfSchool=[SELECT Id, Name, No_Of_Class__c FROM School__c];
        System.debug('####'+updateListOfSchool);
        System.assertEquals('PSL', updateListOfSchool[0].Name);
        
    }
}