Salesforce Training org/objects/Create_Flow_Exception_handling__e.object
<CustomObject>
    <description>Here This Platform Event is use to Create Exception Error in Flow</description>
    <fields>
        <fullName>Element_Category__c</fullName>
        <description>Here This Field Store Category Of element</description>
        <label>Element Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Element_Name__c</fullName>
        <label>Element Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Exception_Message__c</fullName>
        <description>Here This Field is Collect Error Message</description>
        <label>Exception Message</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Flow_Name__c</fullName>
        <description>In This Field Store Flow Name</description>
        <label>Flow Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_API_Name__c</fullName>
        <description>Here This field Store Object API Name</description>
        <label>Object API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_ID__c</fullName>
        <label>Record ID</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Name__c</fullName>
        <label>Record Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Create Flow Exception handling</label>
    <pluralLabel>CreateFlowExceptionhandling</pluralLabel>
</CustomObject>

Salesforce Training org/objects/Flow_Exception__c.object
<CustomObject>
    <fields>
        <fullName>Element_Category__c</fullName>
        <description>Field to hold the Element Category details for which the fault occurred</description>
        <inlineHelpText>Field to hold the Element Category details for which the fault occurred</inlineHelpText>
        <label>Element Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Element_Category</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Element_Name__c</fullName>
        <description>Field to have element name details for which flow exception occurs.</description>
        <inlineHelpText>Field to have element name details for which flow exception occurs.</inlineHelpText>
        <label>Element Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Exception_Message__c</fullName>
        <description>Field to have Flow exception message details.</description>
        <inlineHelpText>Field to have Flow exception message details.</inlineHelpText>
        <label>Exception Message</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Flow_Name__c</fullName>
        <description>Field to have flow name details for which exception occurs.</description>
        <inlineHelpText>Field to have flow name details for which exception occurs.</inlineHelpText>
        <label>Flow Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_API_Name__c</fullName>
        <description>Field to have Object API Name details for which flow executed for.</description>
        <inlineHelpText>Field to have Object API Name details for which flow executed for.</inlineHelpText>
        <label>Object API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_ID__c</fullName>
        <description>Field to have Record ID details for which flow executed for.</description>
        <inlineHelpText>Field to have Record ID details for which flow executed for.</inlineHelpText>
        <label>Record ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Name__c</fullName>
        <label>Record Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Flow Exception</label>
    <nameField>
        <displayFormat>FE-{00000}</displayFormat>
        <label>Flow Exception Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Flow Exceptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce Training org/globalValueSets/Element_Category.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Update Records</fullName>
    </customValue>
    <customValue>
        <fullName>Create Records</fullName>
    </customValue>
    <customValue>
        <fullName>Send Email</fullName>
    </customValue>
    <masterLabel>Element Category</masterLabel>
</GlobalValueSet>

Salesforce Training org/classes/CreateFlowExceptionRecordHandler.cls
/**
*
*  Purpose          :   Apex class of Create Flow Exception Record Handler for Flow 
*
*  Created Date     :   19-05-2023
*
*  Created By       :   Nikunj jain
*
*  Revision Logs    :   V_1.0 - Created
*
**/

public class CreateFlowExceptionRecordHandler 
{
	public static void createFlowExceptionRecord(List<Create_Flow_Exception_handling__e> listOfPlatformEventRecords)
    {
        try
        {
           
            List<Flow_Exception__c> listOfException = new List<Flow_Exception__c>();
        
            if(listOfPlatformEventRecords != null)
            {
                for(Create_Flow_Exception_handling__e ex : listOfPlatformEventRecords)
                {
                    Flow_Exception__c exp = new Flow_Exception__c();
                    
                    exp.Exception_Message__c=ex.Exception_Message__c;
                    exp.Object_API_Name__c=ex.Object_API_Name__c;
                    exp.Element_Category__c=ex.Element_Category__c;
                    exp.Flow_Name__c=exp.Flow_Name__c;
                    exp.Element_Name__c=ex.Element_Name__c;
                    exp.Record_ID__c=ex.Record_ID__c;
                    exp.Record_Name__c=ex.Record_Name__c;
                    
                    
                    listOfException.add(exp);
                }
            }
       
            if(listOfException.size() >0)
            {
                System.debug('@@@@@ listOfException: '+listOfException);
                Utilities.BypassAllTriggers=true;
                insert listOfException;
                Utilities.BypassAllTriggers=false;
            }
        }
        catch(Exception e)
        {
            System.debug('Error Message: '+ e.getMessage());
        }
    }
}