Salesforce Training org/objects/HTTPCalloutConfiguration__mdt.object
<CustomObject>
    <description>This metadata will store the information about all the API callouts that are being used.</description>
    <fields>
        <fullName>Timeout__c</fullName>
        <defaultValue>120000</defaultValue>
        <description>Request Timeout for the API Callout</description>
        <inlineHelpText>Request Timeout for the API Callout</inlineHelpText>
        <label>Timeout</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>HTTPCalloutConfiguration</label>
    <pluralLabel>HTTPCalloutConfigurations</pluralLabel>
</CustomObject>

Salesforce Training org/objects/MetadataDeployment__e.object
<CustomObject>
    <fields>
        <fullName>DeploymentId__c</fullName>
        <label>DeploymentId</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Result__c</fullName>
        <label>Result</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Metadata Deployment</label>
    <pluralLabel>Metadata Deployments</pluralLabel>
</CustomObject>

Salesforce Training org/classes/CreateUpdateCustomMetadataTypeHandler.cls
/**
*
*  Purpose          :   Class to have the methods to create/update custom metadata type records.
						https://andyinthecloud.com/2017/08/29/introducing-custom-metadata-services/
*
*  Created Date     :   11/16/2022
*
*  Created By       :   Abhinav Sharma
*
*  Revision Logs    :   V_1.0 - Created
*
**/
public without sharing class CreateUpdateCustomMetadataTypeHandler 
{
    public static String saveHTTPCalloutConfigurationHandler(String metadataRecordDeveloperName) 
    {
        String deployId = Constants.CHAR_BLANK;
        String deployResult = Constants.CHAR_BLANK;
        
        if(String.isNotBlank(metadataRecordDeveloperName)) 
        {
            List<HTTPCalloutConfiguration__mdt> httpCalloutConfigRecords = [SELECT DeveloperName, Label, Timeout__c
                                                                            FROM HTTPCalloutConfiguration__mdt
                                                                            where DeveloperName =: metadataRecordDeveloperName];
            if(httpCalloutConfigRecords.size() > 0) 
            {
                HTTPCalloutConfiguration__mdt httpCalloutConfigRecord = httpCalloutConfigRecords[0];
                httpCalloutConfigRecord.Timeout__c = 11000;
                
                DeployId = 
                    CustomMetadata.Operations
                    .callback
                    (
                        MetadataDeployment__e.getSObjectType(),
                        MetadataDeployment__e.DeploymentId__c, 
                        MetadataDeployment__e.Result__c
                    )
                    .enqueueUpsertRecords
                    (
                        new List<SObject> { httpCalloutConfigRecord }
                    )
                    .deployId;
            } 
        }
        return deployId;
    }
}