Salesforce Training org/objects/School__c.object
<CustomObject>
    <label>School</label>
    <nameField>
        <label>School Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schools</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Salesforce Training org/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School</label>
        <referenceTo>School__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Salesforce Training org/classes/AssessmentStudentHandler.cls
/**
 * Purpose     : Practice
 * 
 * Created By  : Nikunj jain
 * 
 * Create Date : 20-03-2023
 * 
 * Resion Log  :
 *
*/
public Without sharing class AssessmentStudentHandler 
{
    public static void insertionAndDeletionOfStudent(List<Student__c>listOfStudent, Map<Id,Student__c>mapOfStudent)
    {
     
        if(listOfStudent != null || mapOfStudent != null)
        {
            Set<id>setOfParentId = new Set<Id>();
            
            for(Student__c std:listOfStudent != null ? listOfStudent : mapOfStudent.Values())
            {
                    setOfParentId.add(std.School__c);
            }
            
           
            
            if(setOfParentId != null )
            {
                List<School__c>listOfSchoolName=[SELECT Id, Name  FROM School__c WHERE Id =:setOfParentId];
               
                if(listOfSchoolName!= null && listOfSchoolName.size() > 0)
                {
                 
                    AssesmentPractice.NoOfStudent(listOfSchoolName[0].Name);
                }
            }
        }
    }
     
        
}